---
title: "Simulation of neutrophil development"
author: "Feng Zeng"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

R code to demonstrate the use of scSimulator for simulation of complex cell population.

## Demo code
```{r message=FALSE, warning=FALSE, fig.width=8, fig.height=8}
library(Biobase)
library(Seurat)
library(parallel)
library(doSNOW)
library(scSimulator)


# bulk data of neutrophil 
data(neutrophil)
diff <- grep("DIFF", colnames(neutrophil), value = T)
neutrophil <- neutrophil[, diff]
meta <- data.frame(time = factor(as.numeric(sapply(colnames(neutrophil), ExtractField, 3, "\\."))))
rownames(meta) <- colnames(neutrophil)

# drop-seq data
data(dropseq)
m <- ncol(dropseq)

# simulation
n <- 300
sample.ids <- sample(rownames(meta), n, replace = TRUE)

times <- meta[sample.ids, "time"]
names(times) <- paste0("Cell", 1:n)

chunks <- detectCores()
cl<-makeCluster(chunks,type="SOCK")
registerDoSNOW(cl)
progress <- function(n) cat(sprintf("task %d is complete\n", n))
opts <- list(progress=progress)
X <- foreach(m=split(1:n,1:chunks), .combine='cbind', .options.snow=opts) %dopar% {
  y <- lapply(m, function(i){
    scSimulator::scSimulator(dropseq[,sample(colnames(dropseq),1)], 
                neutrophil[,sample.ids[i]],
                method = "bi",
                lambda = 50)
  })
  y <- do.call('cbind', y)
  colnames(y) <- paste0("Cell", m)
  y
}
rownames(X) <- rownames(neutrophil)


# Using Seurat for tSNE
library(Seurat)
scRNA <- CreateSeuratObject(X, min.cells = 3, min.genes = 30, is.expr = 0)
scRNA@meta.data$time <- times[scRNA@cell.names]


# filtering
scRNA <- FilterCells(scRNA,
                     subset.names=c("nGene", "nUMI"),
                     low.thresholds=c(30, 100),
                     high.thresholds=c(Inf, Inf))

# Normalization
scRNA <- NormalizeData(scRNA)

# Find HVG
scRNA <- FindVariableGenes(scRNA)

# Scaling
scRNA <- ScaleData(scRNA,
                   genes.use=scRNA@var.genes,
                   vars.to.regress=c("nUMI"),
                   model.use="linear",
                   do.cpp=TRUE)


# PCA
scRNA <- RunPCA(scRNA, do.print = FALSE)
PCAPlot(scRNA, dim.1 = 1, dim.2 = 2, group.by = "time")

pc <- as.data.frame(GetCellEmbeddings(scRNA, reduction.type = "pca", dims.use = 1:2))
pca <- qplot(PC1, PC2, data = pc, colour = scRNA@meta.data$time) + 
  scale_colour_discrete(name = "Time") +
  guides(colour = guide_legend(ncol=2,byrow=TRUE))+
  theme(legend.position = c(1,1), legend.justification = c(1,1)) + 
  ggtitle("PCA")

# tSNE
scRNA <- RunTSNE(object = scRNA, 
                 reduction.use = "pca",
                 dims.use = 1:10, 
                 do.fast = FALSE,
                 perplexity = 30,
                 max_iter = 20000,
                 num_threads = 7)

ts <- as.data.frame(GetCellEmbeddings(scRNA, reduction.type = "tsne", dims.use = 1:2))
tse <- qplot(tSNE_1, tSNE_2, data = ts, colour = scRNA@meta.data$time) + 
  scale_colour_discrete(name = "Hour") +
  guides(colour = guide_legend(ncol=2,byrow=TRUE))+
  theme(legend.position = c(1,0), legend.justification = c(1,0)) + 
  ggtitle("")

xy <- tapply(1:nrow(ts), scRNA@meta.data$time, function(i){
  colMeans(ts[i,])
}) 
xy <- do.call("rbind", xy)
xy <- data.frame(xy)
xy$time <- as.numeric(rownames(xy))

tse <- tse + geom_path(data=xy,aes(tSNE_1,tSNE_2),color="grey50")
tse

```

